name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente à meia-noite
  workflow_dispatch: # Permite execução manual

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Generate Snake
        run: |
          npm install
          npm run generate

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: dist/github-snake.svg
